#!/bin/bash
# Script para configurar Cloud SQL no Cloud Run

echo "🔧 CONFIGURANDO CLOUD SQL PARA SEU PROJETO"
echo "=========================================="
echo ""

echo "📋 Informações extraídas:"
echo "- Usuário do banco: derivada"
echo "- Senha do banco: derivada"
echo "- Nome do banco: postgres"
echo "- Projeto: bold-artifact-463813-e9 (assumindo pelo screenshot)"
echo "- Região: us-central1"
echo "- Instância: admin"
echo ""

echo "🛠️ COMANDO PARA EXECUTAR:"
echo "========================="
echo ""
echo "gcloud run services update rrdd-519104831129 \\"
echo "  --region=us-central1 \\"
echo "  --set-env-vars DATABASE_URL='postgresql://derivada:derivada@/postgres?host=/cloudsql/bold-artifact-463813-e9:us-central1:admin' \\"
echo "  --add-cloudsql-instances=bold-artifact-463813-e9:us-central1:admin"
echo ""

echo "📝 EXPLICAÇÃO DA DATABASE_URL:"
echo "=============================="
echo "postgresql://derivada:derivada@/postgres?host=/cloudsql/bold-artifact-463813-e9:us-central1:admin"
echo ""
echo "Partes:"
echo "- derivada:derivada = usuário:senha (do seu banco atual)"
echo "- @/ = sem IP direto (usa proxy)"
echo "- postgres = nome do banco"
echo "- host=/cloudsql/... = conexão via Cloud SQL Proxy"
echo "- bold-artifact-463813-e9:us-central1:admin = CONNECTION_NAME"
echo ""

echo "⚠️ IMPORTANTE VERIFICAR:"
echo "========================"
echo "1. Se o usuário 'derivada' existe no Cloud SQL"
echo "2. Se a senha 'derivada' está correta"
echo "3. Se o banco 'postgres' existe"
echo "4. Se o projeto é realmente 'bold-artifact-463813-e9'"
echo ""

echo "🔍 PARA VERIFICAR O CONNECTION NAME:"
echo "===================================="
echo "No Google Cloud Console:"
echo "1. Vá em SQL > admin"
echo "2. Na aba 'Visão geral'"  
echo "3. Procure por 'Nome da conexão' ou 'Connection name'"
echo "4. Deve ser algo como: PROJETO:REGIÃO:INSTÂNCIA"
echo ""

echo "🧪 TESTE RÁPIDO (opcional):"
echo "=========================="
echo "Se quiser testar primeiro com IP público:"
echo "1. Habilite IP público na instância"
echo "2. Use: DATABASE_URL='postgresql://derivada:derivada@IP_PUBLICO:5432/postgres?sslmode=require'"
echo ""
